import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {validateGraph,parsePlan,layout,descendants} from '../lib/core.mjs';
import {Engine} from '../lib/engine.mjs';
import {safePath} from '../lib/storage.mjs';
const model='claude:haiku';
const node=(id,dependsOn=[])=>({id,title:id,instruction:'Return a useful result',model,dependsOn});
const graph=()=>({nodes:[node('a'),node('b'),node('c',['a','b'])]});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function completed(engine,id){for(let i=0;i<150;i++){const run=engine.run(id);if(!['queued','running'].includes(run.status))return run;await wait(20);}throw new Error('Test timeout');}
function setup(t,execute){const root=fs.mkdtempSync(path.join(os.tmpdir(),'graph-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const engine=new Engine({dataRoot:root,libraryRoot:root,models:[{id:model}],defaultModel:model,concurrency:2},{execute});const p=engine.createProject('Test');p.request='Tiny task';p.graph=graph();engine.saveProject(p);return {engine,p,root};}
test('DAG rejects cycles, missing dependencies, duplicates, unknown models',()=>{assert.equal(validateGraph(graph(),[model]).nodes.length,3);for(const nodes of [[node('a',['b']),node('b',['a'])],[node('a',['missing'])],[node('a'),node('a')],[{...node('a'),model:'invented'}]])assert.throws(()=>validateGraph({nodes},[model]));});
test('planner JSON parsing and deterministic layout',()=>{const g=parsePlan('```json\n'+JSON.stringify(graph())+'\n```');validateGraph(g,[model]);layout(g.nodes);assert.equal(g.nodes[0].y,g.nodes[1].y);assert.ok(g.nodes[2].y>g.nodes[0].y);assert.deepEqual([...descendants(g.nodes,'a')],['a','c']);});
test('path traversal is rejected',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'graph-path-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));assert.equal(safePath(root,'nested'),path.join(root,'nested'));assert.throws(()=>safePath(root,'../secret'));assert.throws(()=>safePath(root,root+'-outside'));});
test('parallel branches run concurrently; join receives both outputs',async t=>{let parallel=0,max=0;const done=[];const {engine,p}=setup(t,async job=>{if(job.title==='c'){assert.deepEqual(done.sort(),['a','b']);assert.match(job.prompt,/result-a/);assert.match(job.prompt,/result-b/);}parallel++;max=Math.max(max,parallel);await wait(70);parallel--;done.push(job.title);return {ok:true,text:'result-'+job.title};});const r=await completed(engine,engine.start(p.id).id);assert.equal(r.status,'done');assert.equal(max,2);assert.match(r.result,/result-c/);assert.ok(fs.existsSync(engine.file('runs',r.id,'result.md')));});
test('failure blocks dependents but independent branch finishes',async t=>{const calls=[];const {engine,p}=setup(t,async job=>{calls.push(job.title);return job.title==='a'?{ok:false,error:'Model unavailable'}:{ok:true,text:'ok'};});const r=await completed(engine,engine.start(p.id).id);assert.equal(r.status,'failed');assert.equal(r.states.b.status,'done');assert.equal(r.states.c.status,'blocked');assert.deepEqual(calls.sort(),['a','b']);});
test('retry reuses unchanged branch and creates immutable history',async t=>{const calls=[];const {engine,p}=setup(t,async job=>{calls.push(job.title);return{ok:true,text:'ok'};});const old=await completed(engine,engine.start(p.id).id);calls.length=0;const retried=await completed(engine,engine.retry(old.id,'a').id);assert.equal(retried.status,'done');assert.deepEqual(calls,['a','c']);assert.equal(retried.states.b.reusedFrom,old.id);assert.notEqual(retried.id,old.id);assert.equal(engine.run(old.id).status,'done');});
test('request changes invalidate reused results',async t=>{const calls=[];const {engine,p}=setup(t,async job=>{calls.push(job.title);return{ok:true,text:'ok'};});const old=await completed(engine,engine.start(p.id).id);engine.updateProject(p.id,{request:'Changed task'});calls.length=0;await completed(engine,engine.retry(old.id,'c').id);assert.deepEqual(calls.sort(),['a','b','c']);});
test('cancellation stops queued joins and cannot report done',async t=>{const {engine,p}=setup(t,async()=>{await wait(100);return {ok:true,text:'ok'};});const started=engine.start(p.id);engine.stop(started.id);const r=await completed(engine,started.id);assert.equal(r.status,'cancelled');assert.equal(r.states.c.status,'cancelled');});
test('project edits and duplicate starts rejected while running',async t=>{const {engine,p}=setup(t,async()=>{await wait(50);return{ok:true,text:'ok'};});const r=engine.start(p.id);assert.throws(()=>engine.updateProject(p.id,{title:'changed'}));assert.throws(()=>engine.start(p.id));await completed(engine,r.id);});
test('invalid planner result fails without replacing graph',async t=>{const {engine,p}=setup(t,async()=>({ok:true,text:'{"nodes":[]}'}));const r=await completed(engine,(await engine.plan(p.id)).id);assert.equal(r.status,'failed');assert.match(r.error,/от 1 до 12/);assert.equal(engine.project(p.id).graph.nodes.length,3);});
test('valid planner proposal persists with selected models',async t=>{const {engine,p}=setup(t,async()=>({ok:true,text:JSON.stringify({...graph(),title:'Real plan'})}));const r=await completed(engine,(await engine.plan(p.id)).id);assert.equal(r.status,'done');const saved=engine.project(p.id);assert.equal(saved.title,'Real plan');assert.ok(saved.graph.nodes[2].y>saved.graph.nodes[0].y);});
test('restart marks unfinished runs interrupted and signals workers',t=>{const {engine,p}=setup(t,async()=>({ok:true,text:'ok'}));const r=engine.makeRun(p,'execution',p.graph);engine.recover();assert.equal(engine.run(r.id).status,'interrupted');assert.ok(fs.existsSync(engine.file('runs',r.id,'cancel')));});
test('lessons persist and attachments are snapshotted',t=>{const {engine,p,root}=setup(t,async()=>({ok:true,text:'ok'}));fs.writeFileSync(path.join(root,'note.md'),'reference data');engine.updateProject(p.id,{attachments:['note.md']});engine.lesson(p.id,'Prefer short answers');const r=engine.makeRun(engine.project(p.id),'execution',p.graph);fs.writeFileSync(path.join(root,'note.md'),'updated');assert.match(r.context,/reference data/);assert.equal(engine.project(p.id).lessons[0].text,'Prefer short answers');});
