import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import http from 'node:http';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
test('HTTP: local boundary, CSRF, traversal, persistent project roundtrip',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'graph-http-'));
 const socket=net.createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(r=>socket.close(r));
 const configFile=path.join(root,'test-config.json');fs.writeFileSync(configFile,JSON.stringify({port,libraryRoot:root,dataRoot:root,herdrPath:'missing-test-herdr',claudePath:'',codexPath:'',models:[{id:'claude:haiku'}],defaultModel:'claude:haiku',concurrency:2,timeoutMs:1000}));
 const child=spawn(process.execPath,['server.mjs'],{env:{...process.env,GRAPH_PORT:String(port),GRAPH_DATA_ROOT:root,GRAPH_CONFIG_FILE:configFile},stdio:'ignore',windowsHide:true});
 const closed=once(child,'close');
 t.after(async()=>{if(child.exitCode===null)child.kill();await closed;fs.rmSync(root,{recursive:true,force:true});});
 const base=`http://127.0.0.1:${port}`;
 let ready=false;for(let i=0;i<80;i++){try{const r=await fetch(base+'/api/projects');if(r.ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,50));}assert.ok(ready,'server started');
 assert.equal((await fetch(base+'/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,403);
 assert.equal((await fetch(base+'/api/projects',{headers:{Origin:'https://attacker.example'}})).status,403);
 const wrongHost=await new Promise((resolve,reject)=>{http.get(base+'/api/projects',{headers:{Host:'attacker.example'}},res=>{res.resume();resolve(res.statusCode);}).on('error',reject);});assert.equal(wrongHost,403);
 assert.equal((await fetch(base+'/api/file?path=../../private.txt')).status,400);
 assert.equal((await fetch(base+'/api/runs/bad-id')).status,400);
 const headers={'Content-Type':'application/json','X-Graph-Client':'studio'};
 const p=await (await fetch(base+'/api/projects',{method:'POST',headers,body:JSON.stringify({title:'HTTP test'})})).json();
 const saved=await fetch(base+'/api/projects/'+p.id,{method:'PUT',headers,body:JSON.stringify({request:'Persist me'})});assert.equal(saved.status,200);
 assert.equal((await fetch(base+'/api/projects/'+p.id+'/continue',{method:'POST',headers,body:JSON.stringify({nodeId:'missing'})})).status,400);
 const reloaded=await (await fetch(base+'/api/projects/'+p.id)).json();assert.equal(reloaded.request,'Persist me');
 assert.equal((await fetch(base+'/api/projects/'+p.id,{method:'POST',headers,body:'{}'})).status,404);
 const cycle={nodes:[{id:'a',title:'A',instruction:'test',model:'claude:haiku',dependsOn:['a']}]};
 assert.equal((await fetch(base+'/api/projects/'+p.id,{method:'PUT',headers,body:JSON.stringify({graph:cycle})})).status,400);
 assert.deepEqual((await (await fetch(base+'/api/projects/'+p.id)).json()).graph,{nodes:[]});
 const layout={name:'HTTP workspace',tree:{type:'leaf',id:'window_a',nodeId:null}};
 const savedLayout=await (await fetch(base+'/api/projects/'+p.id+'/workspaces',{method:'POST',headers,body:JSON.stringify(layout)})).json();
 assert.ok(savedLayout.id);
 assert.equal((await (await fetch(base+'/api/projects/'+p.id+'/workspaces')).json())[0].name,layout.name);
 assert.equal((await fetch(base+'/api/projects/'+p.id+'/workspaces',{method:'POST',headers,body:JSON.stringify({...layout,tree:{type:'split',axis:'row',ratio:2}})})).status,400);
 assert.equal((await fetch(base+'/api/projects/'+p.id+'/workspaces/'+savedLayout.id,{method:'DELETE',headers,body:'{}'})).status,200);
 assert.deepEqual(await (await fetch(base+'/api/projects/'+p.id+'/workspaces')).json(),[]);
 assert.equal((await fetch(base+'/api/sessions/missing/a/control',{method:'POST',headers,body:'{"action":"pause"}'})).status,400);
 for(const asset of ['session-workspace.js','workspace-layout.js','sessions.css','assets/openai.svg','assets/claude.svg'])assert.equal((await fetch(base+'/'+asset)).status,200,asset);
});
