import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {Engine} from '../lib/engine.mjs';
async function finish(e,r){for(let i=0;i<200;i++){if(!e.busy.has(r.id))return e.run(r.id);await new Promise(r=>setTimeout(r,10));}throw Error('timeout');}
function setup(t,execute){const root=fs.mkdtempSync(path.join(os.tmpdir(),'graph-master-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const e=new Engine({dataRoot:path.join(root,'data'),libraryRoot:root,models:[{id:'codex:m'}],defaultModel:'codex:m',concurrency:2},{execute});const p=e.createProject();p.graph={nodes:[{id:'old',title:'Old',instruction:'Original task',model:'codex:m',dependsOn:[]}]};e.saveProject(p);return {e,p};}
test('master continuation preserves earlier results, passes context, expands and executes new nodes',async t=>{const calls=[];const {e,p}=setup(t,async job=>{calls.push(job);if(job.kind==='planner'){assert.match(job.prompt,/original-result/);assert.match(job.prompt,/Environment opened/);return {ok:true,text:JSON.stringify({nodes:[{id:'new',title:'New',instruction:'Use previous work',model:'codex:m',dependsOn:[]}]})};}if(job.title==='New')assert.match(job.prompt,/original-result/);return {ok:true,text:job.title==='Old'?'original-result':'new-result'};});const old=await finish(e,e.start(p.id));const project=e.project(p.id);project.graph.nodes.push({id:'master_next',type:'master',title:'Next prompt',instruction:'Environment opened',model:'codex:m',dependsOn:['old']});e.updateProject(p.id,project);calls.length=0;const continued=await finish(e,e.start(p.id));assert.equal(continued.status,'done');assert.equal(continued.graph.nodes.length,3);assert.equal(continued.states.old.reusedFrom,old.id);assert.deepEqual(calls.map(j=>j.title),['Next prompt','New']);assert.equal(e.run(old.id).graph.nodes.length,1);assert.match(continued.result,/new-result/);assert.equal(e.project(p.id).graph.nodes.length,3);calls.length=0;await finish(e,e.start(p.id));assert.equal(calls.length,0);const changed=e.project(p.id);changed.graph.nodes.find(n=>n.type==='master').instruction='Changed';assert.throws(()=>e.updateProject(p.id,changed));});
test('failed master plan leaves previous graph intact and can be retried',async t=>{const {e,p}=setup(t,async job=>job.kind==='planner'?{ok:true,text:'invalid json'}:{ok:true,text:'old'});await finish(e,e.start(p.id));const project=e.project(p.id);project.graph.nodes.push({id:'master_next',type:'master',title:'Next',instruction:'Continue',model:'codex:m',dependsOn:['old']});e.updateProject(p.id,project);const r=await finish(e,e.start(p.id));assert.equal(r.status,'failed');assert.equal(r.states.old.status,'done');assert.equal(e.project(p.id).graph.nodes.length,2);});

test('continuation finds historical result behind failed runs and ignores cache version or workspace changes',async t=>{
 const calls=[];const {e,p}=setup(t,async job=>{calls.push(job);return job.kind==='planner'?{ok:true,text:JSON.stringify({nodes:[{id:'new',title:'New',instruction:'Next',model:'codex:m',dependsOn:[]}]})}:{ok:true,text:'saved-original'};});
 const old=await finish(e,e.start(p.id));delete old.policyHash;delete old.dataProtocolVersion;e.saveRun(old);
 const project=e.project(p.id);project.workingDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'graph-continue-work-'));t.after(()=>fs.rmSync(project.workingDirectory,{recursive:true,force:true}));
 project.graph.nodes.push({id:'master',type:'master',title:'Continue',instruction:'Next',model:'codex:m',dependsOn:['old']});
 project.graph.nodes.push({id:'unrelated',title:'Unrelated',instruction:'Do not run',model:'codex:m',dependsOn:[]});e.updateProject(p.id,project);
 const failed=e.makeRun(project,'execution',project.graph);failed.status='failed';failed.states.old={status:'failed'};e.saveRun(failed);calls.length=0;
 const result=await finish(e,e.start(p.id));assert.equal(result.status,'done');assert.equal(result.continuation.sourceRunId,old.id);assert.deepEqual(calls.map(x=>x.title),['Continue','New']);assert.match(calls[0].prompt,/saved-original/);assert.equal(result.states.old.reusedFrom,old.id);assert.ok(!result.states.unrelated);assert.ok(e.project(p.id).graph.nodes.some(n=>n.id==='unrelated'));
});
test('continuation fails without historical result or after node edits instead of replaying ancestors',async t=>{
 let calls=0;const {e,p}=setup(t,async()=>{calls++;return {ok:true,text:'saved'};});
 const project=e.project(p.id);project.graph.nodes.push({id:'master',type:'master',title:'Continue',instruction:'Next',model:'codex:m',dependsOn:['old']});e.updateProject(p.id,project);
 assert.throws(()=>e.continueMaster(p.id,'master'),/Нет сохранённого/);assert.equal(calls,0);
 const baseline=e.makeRun(p,'execution',p.graph);baseline.status='done';baseline.states.old={status:'done',result:'original'};e.saveRun(baseline);
 project.graph.nodes[0].instruction='Changed task';e.updateProject(p.id,project);assert.throws(()=>e.start(p.id),/Нет сохранённого/);assert.equal(calls,0);
});
test('continuation refuses changed artifacts without executing old work',async t=>{
 let calls=0;const {e,p}=setup(t,async()=>{calls++;return {ok:true,text:'saved'};});const old=await finish(e,e.start(p.id));const artifact=path.join(e.config.libraryRoot,'result.txt');fs.writeFileSync(artifact,'changed');old.states.old.artifacts=[{path:artifact,relativePath:'result.txt',sha256:'old-hash'}];e.saveRun(old);
 const project=e.project(p.id);project.graph.nodes.push({id:'master',type:'master',title:'Continue',instruction:'Next',model:'codex:m',dependsOn:['old']});e.updateProject(p.id,project);calls=0;assert.throws(()=>e.start(p.id),/Артефакты/);assert.equal(calls,0);
});
