import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {Engine} from '../lib/engine.mjs';import {parseOutcome} from '../lib/outcome.mjs';import {inspectCapabilities} from '../lib/capabilities.mjs';import {agentArgs} from '../lib/worker-runtime.mjs';
function setup(t,execute){const root=fs.mkdtempSync(path.join(os.tmpdir(),'graph-outcome-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const e=new Engine({dataRoot:root,libraryRoot:root,models:[{id:'codex:m'}],defaultModel:'codex:m',concurrency:1},{execute});const p=e.createProject();p.graph={nodes:[{id:'publish',title:'Publish',instruction:'Publish release',model:'codex:m',dependsOn:[]},{id:'result',title:'Result',instruction:'Summarize',model:'codex:m',dependsOn:['publish']}]};e.saveProject(p);return {e,p};}
async function finish(e,r){while(e.busy.has(r.id))await new Promise(resolve=>setTimeout(resolve,10));return e.run(r.id);}
test('blocked publication remains visible as final result and does not run success-dependent node',async t=>{let calls=0;const {e,p}=setup(t,async job=>{calls++;assert.match(job.prompt,/graph-outcome/);return {ok:true,text:'Релиз не опубликован: нет доступа.\n<!-- graph-outcome: {"status":"blocked","summary":"Нет доступа к GitHub"} -->'};});const r=await finish(e,e.start(p.id));assert.equal(calls,1);assert.equal(r.status,'failed');assert.equal(r.states.publish.outcome.status,'blocked');assert.equal(r.states.result.status,'blocked');assert.match(r.result,/Релиз не опубликован/);assert.match(fs.readFileSync(e.file('runs',r.id,'result.md'),'utf8'),/Нет доступа/);assert.doesNotMatch(r.states.publish.result,/graph-outcome/);});
test('CLI failure keeps partial agent answer in final run result',async t=>{const {e,p}=setup(t,async()=>({ok:false,error:'network denied',text:'Изменения локально готовы; релиз не опубликован.'}));const r=await finish(e,e.start(p.id));assert.match(r.result,/Изменения локально готовы/);assert.match(r.result,/network denied/);});
test('historical failed run without result is readable without rewriting history',t=>{const {e,p}=setup(t,async()=>{});const r=e.makeRun(p,'execution',p.graph);r.status='failed';r.states.publish={status:'failed',error:'historical failure',result:'Old explanation'};r.states.result={status:'blocked'};e.saveRun(r);const before=fs.readFileSync(e.file('runs',r.id,'state.json'),'utf8');assert.match(e.run(r.id).result,/Old explanation/);assert.equal(fs.readFileSync(e.file('runs',r.id,'state.json'),'utf8'),before);});
test('missing source workspace blocks execution before a model call',async t=>{let calls=0;const {e,p}=setup(t,async()=>{calls++;});p.graph.nodes[0].requiresWorkspace=true;e.saveProject(p);const r=await finish(e,e.start(p.id));assert.equal(calls,0);assert.match(r.result,/Не выбрана рабочая папка/);});
test('GitHub readiness reports missing auth and target without disclosing CLI output',async()=>{const report=await inspectCapabilities({}, {},{run:async(file,args)=>{if(args[0]==='auth')throw Object.assign(Error('secret-token'),{code:1});return {stdout:''};}});assert.equal(report.githubReady,false);assert.ok(report.checks.some(c=>c.id==='github-auth'&&!c.ok));assert.ok(!JSON.stringify(report).includes('secret-token'));});
test('task status contract and scoped network configuration',()=>{assert.equal(parseOutcome('Done').outcome.status,'unreported');assert.equal(parseOutcome('Text\n<!-- graph-outcome: {"status":"partial","summary":"No release"} -->').outcome.status,'partial');const job={model:'codex:m',dir:os.tmpdir(),kind:'execution',githubRepository:'owner/repo'};assert.ok(agentArgs(job).includes('sandbox_workspace_write.network_access=true'));assert.ok(!agentArgs({...job,kind:'planner'}).includes('sandbox_workspace_write.network_access=true'));assert.ok(!agentArgs({...job,githubRepository:''}).includes('sandbox_workspace_write.network_access=true'));});
import {githubEnvironment} from '../lib/worker-runtime.mjs';
test('GitHub auth is passed only in executor environment and never in job data',async()=>{const job={kind:'execution',githubRepository:'owner/repo',config:{ghPath:'gh-test',githubAgentAuth:true}};const original=JSON.stringify(job);let call;const env=await githubEnvironment(job,{PATH:'path'},{command:async(file,args)=>{call={file,args};return {stdout:'fake-test-credential\n'};}});assert.equal(env.GH_TOKEN,'fake-test-credential');assert.deepEqual(call.args,['auth','token','--hostname','github.com']);assert.equal(JSON.stringify(job),original);assert.deepEqual(await githubEnvironment({...job,kind:'planner'},{PATH:'path'},{command:()=>{throw Error('must not run');}}),{PATH:'path'});});
