import fs from 'node:fs';
import path from 'node:path';
import {readJSON,writeJSON} from './storage.mjs';
export function resumeCommand(config,node,state,githubRepository=''){
 if(!/^[a-zA-Z0-9_-]{8,120}$/.test(state.sessionId||''))throw new Error('У этой ноды нет сохранённой сессии для продолжения.');
 const [provider]=node.model.split(':'),quote=s=>"'"+String(s).replaceAll("'","''")+"'";
 const args=provider==='claude'?['--resume',state.sessionId,'--permission-mode','default']:['resume',state.sessionId,'--sandbox','workspace-write','--ask-for-approval','on-request','--no-alt-screen'];
 const parts=['Remove-Item Env:CLAUDECODE -ErrorAction SilentlyContinue'];
 const toolPaths=['nodePath','gitPath','ghPath'].map(key=>config[key]).filter(Boolean).map(file=>path.dirname(file));if(toolPaths.length)parts.push('$env:PATH = '+quote(toolPaths.join(path.delimiter)+path.delimiter)+' + $env:PATH');
 if(config.githubAgentAuth&&githubRepository)parts.push('$env:GH_TOKEN = (& '+quote(config.ghPath||'gh')+' auth token --hostname github.com); if ($LASTEXITCODE -ne 0) { throw '+quote('GitHub auth unavailable')+' }');
 parts.push('& '+quote(provider==='claude'?config.claudePath:config.codexPath)+' '+args.map(quote).join(' '));
 return 'powershell.exe -NoProfile -EncodedCommand '+Buffer.from(parts.join('; '),'utf16le').toString('base64');
}
export class Terminals{
 constructor(engine,adapter){this.engine=engine;this.adapter=adapter;this.pending=new Map();}
 file(runId,nodeId){return this.engine.file('terminals',runId,nodeId+'.json');}
 target(runId,nodeId){const run=this.engine.run(runId),node=run.graph.nodes.find(n=>n.id===nodeId),state=run.states[nodeId];if(!node||!state)throw new Error('Сессия ноды не найдена.');return {run,node,state};}
 async open(runId,nodeId){const key=runId+'/'+nodeId;if(this.pending.has(key))return this.pending.get(key);const task=this.create(runId,nodeId);this.pending.set(key,task);try{return await task;}finally{this.pending.delete(key);}}
 async create(runId,nodeId){const {run,node,state}=this.target(runId,nodeId);if(['running','queued'].includes(run.status))throw new Error('Сначала дождитесь завершения графа или остановите его. Текущий вывод доступен во вкладке «Журнал».');const existing=readJSON(this.file(runId,nodeId));if(existing){try{await this.adapter.command('pane','get',existing.pane);const response=await this.adapter.command('agent','get',existing.pane);const agent=response.agent&&typeof response.agent==='object'?response.agent:response;if(agent.agent===existing.provider||Date.now()-(existing.createdAt||0)<20000)return existing;}catch{}}
 const source=state.reusedFrom||runId;const dir=run.workingDirectory||this.engine.file('runs',source,nodeId,'work');if(!fs.existsSync(dir))throw new Error('Рабочая папка сессии недоступна.');const command=resumeCommand(this.engine.config,node,state,run.githubRepository||this.engine.project(run.projectId).githubRepository||'');const workspace=await this.adapter.ensureWorkspace(dir);const tab=await this.adapter.command('tab','create','--workspace',workspace,'--cwd',dir,'--label','Диалог · '+node.title.slice(0,35),'--no-focus');const terminal={createdAt:Date.now(),pane:tab.root_pane.pane_id,runId,nodeId,provider:node.model.split(':')[0],sessionId:state.sessionId};writeJSON(this.file(runId,nodeId),terminal);await this.adapter.command('pane','run',terminal.pane,command);return terminal;
 }
 async status(runId,nodeId){this.target(runId,nodeId);const t=readJSON(this.file(runId,nodeId));if(!t)return {opened:false,text:'Откройте терминал, чтобы продолжить разговор с агентом.'};const output=await this.adapter.command('pane','read',t.pane,'--source','visible','--format','text');let agent=null;try{const result=await this.adapter.command('agent','get',t.pane);agent=(result.agent&&typeof result.agent==='object')?result.agent:result;}catch{}const ready=!!agent&&typeof agent==='object'&&agent.agent===t.provider&&(!agent.agent_session||agent.agent_session.value===t.sessionId);return {opened:true,text:output.text??output.output?.text??'',ready,status:ready?agent.agent_status:'starting',pane:t.pane};}
 async send(runId,nodeId,input){this.target(runId,nodeId);const t=readJSON(this.file(runId,nodeId));if(!t)throw new Error('Сначала откройте терминал.');const status=await this.status(runId,nodeId);if(!status.ready)throw new Error('Агент ещё не готов или уже вышел. Ввод в системную оболочку заблокирован.');if(input.key){if(!['enter','esc','up','down','left','right','tab','ctrl+c'].includes(input.key))throw new Error('Недоступная клавиша.');await this.adapter.command('agent','send-keys',t.pane,input.key);}else{if(typeof input.text!=='string'||!input.text.trim()||input.text.length>16000||/[\x00-\x08\x0b-\x1f\x7f]/.test(input.text))throw new Error('Сообщение должно содержать от 1 до 16 000 символов без управляющих кодов.');await this.adapter.command('agent','prompt',t.pane,input.text);}return {sent:true};}
}
